# Generated by Django 2.2.1 on 2020-10-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('column_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField()),
                ('task_selection_config', models.TextField(null=True)),
                ('kanban_brief_view_config', models.TextField(null=True)),
                ('list_brief_view_config', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=400)),
                ('fields_order', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDisplayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=400)),
                ('display_status', models.CharField(choices=[('HIDE', 'HIDE'), ('SHOW', 'SHOW')], default='SHOW', max_length=20)),
                ('field_id', models.CharField(max_length=200)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_id', models.CharField(max_length=200)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='UserStarredBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Board')),
            ],
            options={
                'unique_together': {('user_id', 'board')},
            },
        ),
    ]
