# Generated by Django 2.2.1 on 2020-07-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='display_name',
        ),
    ]
