# Generated by Django 2.2.1 on 2020-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project_id',
            field=models.CharField(default='project_1', max_length=200),
            preserve_default=False,
        ),
    ]
