# Generated by Django 2.2.1 on 2020-09-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=400)),
                ('fields_order', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDisplayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=400)),
                ('display_status', models.CharField(choices=[('HIDE', 'HIDE'), ('SHOW', 'SHOW')], default='SHOW', max_length=20)),
                ('field_id', models.CharField(max_length=200)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_boards.Column')),
            ],
        ),
    ]
