# Generated by Django 2.2.1 on 2020-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_boards', '0002_board_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='project_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
