# Generated by Django 2.2.1 on 2020-07-24 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ib_boards', '0002_auto_20200724_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='display_name',
            new_name='name',
        ),
    ]
