# Generated by Django 2.2.1 on 2020-07-22 18:57

from django.db import migrations, models
import django.db.models.deletion
import ib_discussions.models.discussion
import ib_discussions.models.discussion_set
import ib_discussions.models.entity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=ib_discussions.models.entity.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('TASK', 'TASK')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionSet',
            fields=[
                ('id', models.UUIDField(default=ib_discussions.models.discussion_set.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField(editable=False)),
                ('entity_type', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('entity_id', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=ib_discussions.models.discussion.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_clarified', models.BooleanField(default=False)),
                ('discussion_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_discussions.DiscussionSet')),
            ],
        ),
    ]
