# Generated by Django 2.2.1 on 2020-08-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='user_id',
            field=models.TextField(),
        ),
    ]
