# Generated by Django 2.2.1 on 2020-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='thumbnail_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
