# Generated by Django 2.2.1 on 2020-09-05 10:29

from django.db import migrations, models
import ib_discussions.models.entity


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='commentwithmentionuserid',
            name='mention_user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='discussionset',
            name='entity_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(max_length=25, validators=[ib_discussions.models.entity.validate_entity_type_for_discussion]),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='thumbnail_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='url',
            field=models.URLField(),
        ),
    ]
