# Generated by Django 2.2.1 on 2020-07-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0002_discussion_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion_set_id',
            new_name='discussion_set',
        ),
    ]
