# Generated by Django 2.2.1 on 2020-07-23 04:59

from django.db import migrations, models
import ib_discussions.models.discussion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0003_auto_20200722_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(default=ib_discussions.models.discussion.get_datetime_now),
        ),
    ]
