# Generated by Django 2.2.1 on 2020-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0004_auto_20200723_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='user_id',
            field=models.UUIDField(editable=False),
        ),
    ]
