# Generated by Django 2.2.1 on 2020-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0005_auto_20200723_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionset',
            name='entity_id',
            field=models.TextField(),
        ),
    ]
