# Generated by Django 2.2.1 on 2020-08-06 10:24

from django.db import migrations, models
import django.db.models.deletion
import ib_discussions.models.comment


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0007_auto_20200803_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=ib_discussions.models.comment.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('discussion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ib_discussions.Discussion')),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ib_discussions.Comment')),
            ],
        ),
    ]
