# Generated by Django 2.2.1 on 2020-08-06 10:40

from django.db import migrations, models
import ib_discussions.models.comment


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=ib_discussions.models.comment.get_datetime_now),
        ),
    ]
