# Generated by Django 2.2.1 on 2020-08-08 11:18

from django.db import migrations, models
import django.db.models.deletion
import ib_discussions.models.multimedia


class Migration(migrations.Migration):

    dependencies = [
        ('ib_discussions', '0009_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMedia',
            fields=[
                ('id', models.UUIDField(default=ib_discussions.models.multimedia.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('format_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO')], max_length=30)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentWithMultiMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_discussions.Comment')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_discussions.MultiMedia')),
            ],
        ),
        migrations.CreateModel(
            name='CommentWithMentionUserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_user_id', models.CharField(max_length=40)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_discussions.Comment')),
            ],
        ),
    ]
