# Generated by Django 2.2.1 on 2020-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion
import ib_utility_tools.models.checklist
import ib_utility_tools.models.checklist_item
import ib_utility_tools.models.timer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.UUIDField(default=ib_utility_tools.models.checklist.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('TASK', 'TASK'), ('COLUMN', 'COLUMN'), ('BOARD', 'BOARD')], max_length=10)),
            ],
            options={
                'unique_together': {('entity_id', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timer_id', models.UUIDField(default=ib_utility_tools.models.timer.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('STAGE_TASK', 'STAGE_TASK')], max_length=10)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('duration_in_seconds', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('entity_id', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('checklist_item_id', models.UUIDField(default=ib_utility_tools.models.checklist_item.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('is_checked', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='ib_utility_tools.Checklist')),
            ],
        ),
    ]
