# Generated by Django 2.2.1 on 2020-09-03 16:11

from django.db import migrations, models
import ib_utility_tools.models.checklist_item


class Migration(migrations.Migration):

    dependencies = [
        ('ib_utility_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='created_at',
            field=models.DateTimeField(default=ib_utility_tools.models.checklist_item.get_datetime_now),
        ),
    ]
