# Generated by Django 2.2.1 on 2020-08-07 19:31

from django.db import migrations, models
import ib_utility_tools.models.timer


class Migration(migrations.Migration):

    dependencies = [
        ('ib_utility_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timer_id', models.UUIDField(default=ib_utility_tools.models.timer.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('STAGE_TASK', 'STAGE_TASK')], max_length=10)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('duration_in_seconds', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('entity_id', 'entity_type')},
            },
        ),
    ]
