# Generated by Django 2.2.1 on 2020-09-05 10:29

from django.db import migrations, models
import ib_utility_tools.models.checklist
import ib_utility_tools.models.timer


class Migration(migrations.Migration):

    dependencies = [
        ('ib_utility_tools', '0002_checklistitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='entity_type',
            field=models.CharField(max_length=25, validators=[ib_utility_tools.models.checklist.validate_entity_type]),
        ),
        migrations.AlterField(
            model_name='timer',
            name='entity_type',
            field=models.CharField(max_length=25, validators=[ib_utility_tools.models.timer.validate_timer_entity_type]),
        ),
    ]
