# Generated by Django 2.2.1 on 2020-08-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
