# Generated by Django 2.2.1 on 2020-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
