# Generated by Django 2.2.1 on 2020-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='field_display_config',
            field=models.TextField(max_length=400),
        ),
    ]
