# Generated by Django 2.2.1 on 2020-07-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='field_display_config',
        ),
    ]
