# Generated by Django 2.2.1 on 2020-08-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageaction',
            name='action_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
