# Generated by Django 2.2.1 on 2020-07-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTemplateGoF',
            new_name='GoFToTaskTemplate',
        ),
        migrations.RenameField(
            model_name='goftotasktemplate',
            old_name='enable_multiple_gofs',
            new_name='enable_add_another_gof',
        ),
        migrations.RenameField(
            model_name='goftotasktemplate',
            old_name='gof_id',
            new_name='gof',
        ),
        migrations.RenameField(
            model_name='goftotasktemplate',
            old_name='template_id',
            new_name='task_template',
        ),
    ]
