# Generated by Django 2.2.1 on 2020-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageaction',
            name='action_type',
            field=models.CharField(default='no validations', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stageaction',
            name='transition_template_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
