# Generated by Django 2.2.1 on 2020-08-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='acted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.StageAction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
