# Generated by Django 2.2.1 on 2020-07-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageaction',
            old_name='stage_id',
            new_name='stage',
        ),
    ]
