# Generated by Django 2.2.1 on 2020-08-06 16:26

from django.db import migrations, models
import ib_tasks.constants.enum


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='is_selected',
            field=models.CharField(default=ib_tasks.constants.enum.Status('ENABLED'), max_length=10),
        ),
    ]
