# Generated by Django 2.2.1 on 2020-07-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgof',
            name='gof_id',
        ),
        migrations.AddField(
            model_name='taskgof',
            name='gof',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.GoF'),
            preserve_default=False,
        ),
    ]
