# Generated by Django 2.2.1 on 2020-08-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageaction',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='stageaction',
            name='transition_template_id',
        ),
        migrations.AddField(
            model_name='taskstage',
            name='stage_assignee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StageRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Stage')),
            ],
        ),
    ]
