# Generated by Django 2.2.1 on 2020-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='is_transition_template',
            field=models.BooleanField(default=False),
        ),
    ]
