# Generated by Django 2.2.1 on 2020-08-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200801_1821'),
        ('ib_tasks', '0002_auto_20200801_1719'),
    ]

    operations = [
    ]
