# Generated by Django 2.2.1 on 2020-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20201003_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
