# Generated by Django 2.2.1 on 2020-08-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200807_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageaction',
            name='transition_template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate'),
        ),
    ]
