# Generated by Django 2.2.1 on 2020-08-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_filter_filtercondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate'),
        ),
    ]
