# Generated by Django 2.2.1 on 2020-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200721_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageaction',
            name='button_color',
            field=models.TextField(null=True),
        ),
    ]
