# Generated by Django 2.2.1 on 2020-07-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200720_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gof',
            name='enable_multiple_gofs',
        ),
        migrations.RemoveField(
            model_name='gof',
            name='order',
        ),
        migrations.RemoveField(
            model_name='gof',
            name='task_template',
        ),
        migrations.CreateModel(
            name='GoFToTaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('enable_add_another_gof', models.BooleanField(default=False)),
                ('gof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.GoF')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='gof',
            name='task_template',
            field=models.ManyToManyField(through='ib_tasks.GoFToTaskTemplate', to='ib_tasks.TaskTemplate'),
        ),
    ]
