# Generated by Django 2.2.1 on 2020-10-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ib_tasks', '0002_auto_20201003_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionTemplateTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             to='ib_tasks.StageAction')),
                ('task', models.ForeignKey(null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='transition_tasks',
                                           to='ib_tasks.Task')),
                ('transition_task', models.ForeignKey(null=True,
                                                      on_delete=django.db.models.deletion.SET_NULL,
                                                      to='ib_tasks.Task')),
            ],
        ),
    ]
