# Generated by Django 2.2.1 on 2020-08-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200806_1634'),
        ('ib_tasks', '0002_tasktemplate_is_transition_template'),
    ]

    operations = [
    ]
