# Generated by Django 2.2.1 on 2020-07-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200720_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gof',
            name='enable_multiple_gofs',
        ),
        migrations.RemoveField(
            model_name='gof',
            name='order',
        ),
        migrations.AlterField(
            model_name='field',
            name='allowed_formats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='error_messages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('PLAIN_TEXT', 'PLAIN_TEXT'), ('PHONE_NUMBER', 'PHONE_NUMBER'), ('EMAIL', 'EMAIL'), ('URL', 'URL'), ('PASSWORD', 'PASSWORD'), ('NUMBER', 'NUMBER'), ('FLOAT', 'FLOAT'), ('LONG_TEXT', 'LONG_TEXT'), ('DROPDOWN', 'DROPDOWN'), ('GOF_SELECTOR', 'GOF_SELECTOR'), ('RADIO_GROUP', 'RADIO_GROUP'), ('CHECKBOX_GROUP', 'CHECKBOX_GROUP'), ('MULTI_SELECT_FIELD', 'MULTI_SELECT_FIELD'), ('MULTI_SELECT_LABELS', 'MULTI_SELECT_LABELS'), ('DATE', 'DATE'), ('TIME', 'TIME'), ('DATE_TIME', 'DATE_TIME'), ('IMAGE_UPLOADER', 'IMAGE_UPLOADER'), ('FILE_UPLOADER', 'FILE_UPLOADER'), ('SEARCHABLE', 'SEARCHABLE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='gof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.GoF'),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='tooltip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='validation_regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='gof',
            name='task_template',
        ),
        migrations.CreateModel(
            name='TaskTemplateGoF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('enable_multiple_gofs', models.BooleanField(default=False)),
                ('gof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.GoF')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='gof',
            name='task_template',
            field=models.ManyToManyField(through='ib_tasks.TaskTemplateGoF', to='ib_tasks.TaskTemplate'),
        ),
    ]
