# Generated by Django 2.2.1 on 2020-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0002_auto_20200807_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='stage_assignee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
