# Generated by Django 2.2.1 on 2020-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20200806_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='is_selected',
            field=models.CharField(default='DISABLED', max_length=10),
        ),
    ]
