# Generated by Django 2.2.1 on 2020-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20200806_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtercondition',
            old_name='field_id',
            new_name='field',
        ),
    ]
