# Generated by Django 2.2.1 on 2020-08-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_merge_20200806_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_selected', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('GTE', 'GTE'), ('LTE', 'LTE'), ('GT', 'GT'), ('LT', 'LT'), ('NE', 'NE'), ('EQ', 'EQ'), ('CONTAINS', 'CONTAINS')], max_length=100)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Field')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Filter')),
            ],
        ),
    ]
