# Generated by Django 2.2.1 on 2020-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_taskstagerp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM')], default='HIGH', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(default='test_project', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskdelayreason',
            name='due_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='taskgof',
            unique_together={('task', 'gof', 'same_gof_order')},
        ),
    ]
