# Generated by Django 2.2.1 on 2020-08-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_merge_20200805_1105'),
        ('ib_tasks', '0003_merge_20200804_2236'),
    ]

    operations = [
    ]
