# Generated by Django 2.2.1 on 2020-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_taskstagerp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taskgof',
            unique_together={('task', 'gof', 'same_gof_order')},
        ),
    ]