# Generated by Django 2.2.1 on 2020-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20200808_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='created_by',
            field=models.CharField(max_length=120),
        ),
    ]
