# Generated by Django 2.2.1 on 2020-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20200822_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='project_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
