# Generated by Django 2.2.1 on 2020-10-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20201004_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionTemplateTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ib_tasks.StageAction')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ib_tasks.Task')),
            ],
        ),
    ]
