# Generated by Django 2.2.1 on 2020-08-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_auto_20200807_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageaction',
            old_name='transition_template_id',
            new_name='transition_template',
        ),
    ]
