# Generated by Django 2.2.1 on 2020-09-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0003_taskstagerp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskgof',
            unique_together={('task', 'gof', 'same_gof_order')},
        ),
    ]
