# Generated by Django 2.2.1 on 2020-10-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ib_tasks', '0004_transitiontemplatetasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitiontemplatetasks',
            name='transition_task',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='ib_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='transitiontemplatetasks',
            name='task',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='transition_tasks',
                                    to='ib_tasks.Task'),
        ),
    ]
