# Generated by Django 2.2.1 on 2020-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0004_auto_20200901_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskdelayreason',
            name='due_datetime',
            field=models.DateTimeField(),
        ),
    ]
