# Generated by Django 2.2.1 on 2020-08-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0004_filter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskstagehistory',
            name='team_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
