# Generated by Django 2.2.1 on 2020-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0004_transitiontemplatetasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
