# Generated by Django 2.2.1 on 2020-09-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0004_auto_20200903_1240'),
        ('ib_tasks', '0004_auto_20200901_1556'),
    ]

    operations = [
    ]
