# Generated by Django 2.2.1 on 2020-08-06 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0004_merge_20200805_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='acted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.StageAction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
