# Generated by Django 2.2.1 on 2020-08-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_auto_20200808_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTaskStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Stage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Task')),
            ],
            options={
                'unique_together': {('stage', 'task')},
            },
        ),
        migrations.DeleteModel(
            name='TaskStage',
        ),
    ]
