# Generated by Django 2.2.1 on 2020-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_merge_20200904_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskdelayreason',
            name='due_datetime',
            field=models.DateTimeField(),
        ),
    ]
