# Generated by Django 2.2.1 on 2020-08-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_auto_20200824_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdelayreason',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Stage'),
            preserve_default=False,
        ),
    ]
