# Generated by Django 2.2.1 on 2020-09-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_auto_20200903_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstagerp',
            unique_together={('task', 'stage', 'rp_id')},
        ),
    ]
