# Generated by Django 2.2.1 on 2020-08-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_auto_20200824_1128'),
        ('ib_tasks', '0005_auto_20200824_0921'),
    ]

    operations = [
    ]
