# Generated by Django 2.2.1 on 2020-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0005_auto_20200808_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_display_id',
            field=models.CharField(default='iB_001', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
