# Generated by Django 2.2.1 on 2020-08-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0006_taskduedetails_taskreasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskduedetails',
            old_name='reason',
            new_name='task_reason',
        ),
        migrations.RenameField(
            model_name='taskreasons',
            old_name='reason_choice',
            new_name='reason',
        ),
    ]
