# Generated by Django 2.2.1 on 2020-09-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0006_stageflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageflow',
            name='previous_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_stages', to='ib_tasks.Stage'),
        ),
        migrations.AlterUniqueTogether(
            name='stageflow',
            unique_together={('previous_stage', 'action', 'next_stage')},
        ),
    ]
