# Generated by Django 2.2.1 on 2020-09-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ib_tasks', '0006_auto_20200916_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_task',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task',
                                      to='ib_tasks.Task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks',
                                           to='ib_tasks.Task')),
            ],
        ),
    ]
