# Generated by Django 2.2.1 on 2020-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0006_auto_20200905_1157'),
        ('ib_tasks', '0005_auto_20200903_1737'),
    ]

    operations = [
    ]
