# Generated by Django 2.2.1 on 2020-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_auto_20200811_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstagehistory',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskstagehistory',
            name='joined_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskstagehistory',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
