# Generated by Django 2.2.1 on 2020-09-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpermittedroles',
            name='role_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldrole',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stagepermittedroles',
            name='role_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_display_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='fieldrole',
            index=models.Index(fields=['role', 'permission_type'], name='ib_tasks_fi_role_a42d35_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['project_id', 'is_selected', 'created_by'], name='ib_tasks_fi_project_97e5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['project_id', 'created_by'], name='ib_tasks_fi_project_7eb0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gofrole',
            index=models.Index(fields=['role', 'permission_type'], name='ib_tasks_go_role_79f951_idx'),
        ),
    ]
