# Generated by Django 2.2.1 on 2020-08-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_taskstagehistory'),
        ('ib_tasks', '0007_task_task_display_id'),
    ]

    operations = [
    ]
