# Generated by Django 2.2.1 on 2020-09-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_auto_20200907_1106'),
        ('ib_tasks', '0006_auto_20200905_1157'),
    ]

    operations = [
    ]
