# Generated by Django 2.2.1 on 2020-08-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0006_usertaskdelayreason'),
        ('ib_tasks', '0007_task_task_display_id'),
    ]

    operations = [
    ]

