# Generated by Django 2.2.1 on 2020-08-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_auto_20200812_1655'),
        ('ib_tasks', '0006_usertaskdelayreason'),
    ]

    operations = [
    ]
