# Generated by Django 2.2.1 on 2020-08-10 16:17

from django.db import migrations, models
import django.db.models.deletion
import ib_tasks.constants.enum


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_auto_20200810_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskDelayReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_datetime', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('reason_id', models.CharField(choices=[(ib_tasks.constants.enum.DelayReasons('wrong estimation of time'), 'wrong estimation of time'), (ib_tasks.constants.enum.DelayReasons('Execution level plan fail'), 'Execution level plan fail'), (ib_tasks.constants.enum.DelayReasons('No clarity in objective'), 'No clarity in objective'), (ib_tasks.constants.enum.DelayReasons("Doesn't follow Instructions"), "Doesn't follow Instructions"), (ib_tasks.constants.enum.DelayReasons('others'), 'others')], max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskreasons',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskDueDetails',
        ),
        migrations.DeleteModel(
            name='TaskReasons',
        ),
    ]
