# Generated by Django 2.2.1 on 2020-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_display_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
