# Generated by Django 2.2.1 on 2020-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_task_task_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_display_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
