# Generated by Django 2.2.1 on 2020-08-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_auto_20200811_2203'),
        ('ib_tasks', '0007_task_task_display_id'),
    ]

    operations = [
    ]
