# Generated by Django 2.2.1 on 2020-08-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0007_taskstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_display_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
