# Generated by Django 2.2.1 on 2020-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0008_auto_20200929_1634'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filter',
            name='ib_tasks_fi_project_9d3349_idx',
        ),
        migrations.AlterField(
            model_name='filter',
            name='project_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['project_id', 'is_selected', 'created_by'], name='ib_tasks_fi_project_97e5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['project_id', 'created_by'], name='ib_tasks_fi_project_7eb0ab_idx'),
        ),
    ]
