# Generated by Django 2.2.1 on 2020-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ib_tasks', '0008_auto_20200929_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageaction',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
