# Generated by Django 2.2.1 on 2020-08-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0008_auto_20200812_1214'),
        ('ib_tasks', '0008_merge_20200811_2216'),
    ]

    operations = [
    ]
