# Generated by Django 2.2.1 on 2020-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0008_auto_20200929_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
