# Generated by Django 2.2.1 on 2020-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0009_auto_20201001_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gof',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
