# Generated by Django 2.2.1 on 2020-10-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0010_tasktemplatemandatoryfields'),
        ('ib_tasks', '0010_auto_20201001_1212'),
    ]

    operations = [
    ]
