# Generated by Django 2.2.1 on 2020-10-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0011_merge_20201001_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
