# Generated by Django 2.2.1 on 2020-10-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0011_tasktemplatemandatoryfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.StageAction'),
        ),
    ]
