# Generated by Django 2.2.1 on 2020-10-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_tasks', '0012_field_is_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTemplateGlobalConstants',
        ),
        migrations.DeleteModel(
            name='TaskTemplateStatusVariables',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='tasktemplatestatusvariable',
            name='task_template_id',
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplatestatusvariable',
            name='task_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ib_tasks.TaskTemplate'),
            preserve_default=False,
        ),
    ]
