# Generated by Django 2.2.1 on 2020-07-14 16:37

from django.db import migrations, models
import ib_iam.models.role


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=ib_iam.models.role.generate_uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.CharField(max_length=30, unique=True)),
                ('role_name', models.CharField(max_length=30)),
                ('role_description', models.CharField(max_length=120)),
            ],
        ),
    ]
