# Generated by Django 2.2.1 on 2020-10-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthtoken',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
