# Generated by Django 2.2.1 on 2020-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('role_id', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='userteam',
            unique_together={('user_id', 'team')},
        ),
    ]
