# Generated by Django 2.2.1 on 2020-07-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='member_id',
            new_name='user_id',
        ),
    ]
