# Generated by Django 2.2.1 on 2020-08-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('role_id', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='userteam',
            unique_together={('user_id', 'team')},
        ),
    ]
