# Generated by Django 2.2.1 on 2020-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
