# Generated by Django 2.2.1 on 2020-07-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='display_name',
            new_name='name',
        ),
    ]
