# Generated by Django 2.2.1 on 2020-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0002_auto_20200903_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
