# Generated by Django 2.2.1 on 2020-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0002_auto_20200826_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_id',
            field=models.CharField(default='FINMAN', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
