# Generated by Django 2.2.1 on 2020-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0002_auto_20200903_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elasticuserintermediary',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='cover_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
    ]
