# Generated by Django 2.2.1 on 2020-08-14 17:48

from django.db import migrations, models
import django.db.models.deletion
import ib_iam.models.team_member_level


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0002_city_country_elasticuserintermediary_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberLevel',
            fields=[
                ('id', models.UUIDField(default=ib_iam.models.team_member_level.generate_uuid, primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=200)),
                ('level_hierarchy', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_iam.Team')),
            ],
        ),
    ]
