# Generated by Django 2.2.1 on 2020-07-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0002_auto_20200723_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
