# Generated by Django 2.2.1 on 2020-09-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0003_auto_20200905_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
