# Generated by Django 2.2.1 on 2020-08-21 10:06

from django.db import migrations, models
import django.db.models.deletion
import ib_iam.models.team_member_level


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0003_auto_20200820_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='immediate_superior_team_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ib_iam.UserTeam'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='TeamMemberLevel',
            fields=[
                ('id', models.UUIDField(default=ib_iam.models.team_member_level.generate_uuid, primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=200)),
                ('level_hierarchy', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_iam.Team')),
            ],
            options={
                'unique_together': {('team', 'level_hierarchy', 'level_name')},
            },
        ),
        migrations.AddField(
            model_name='userteam',
            name='team_member_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ib_iam.TeamMemberLevel'),
        ),
    ]
