# Generated by Django 2.2.1 on 2020-08-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0003_auto_20200820_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cover_page_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ib_iam.Team'),
        ),
    ]
