# Generated by Django 2.2.1 on 2020-08-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0003_teammemberlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='immediate_superior_team_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_iam.UserTeam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='team_member_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_iam.TeamMemberLevel'),
        ),
        migrations.AlterUniqueTogether(
            name='teammemberlevel',
            unique_together={('team', 'level_hierarchy', 'level_name')},
        ),
    ]
