# Generated by Django 2.2.1 on 2020-08-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0004_auto_20200821_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTeam',
            new_name='TeamUser',
        ),
    ]
