# Generated by Django 2.2.1 on 2020-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0004_auto_20200905_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
