# Generated by Django 2.2.1 on 2020-08-22 12:39

from django.db import migrations, models
import ib_iam.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0004_auto_20200821_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=ib_iam.models.project.generate_uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
