# Generated by Django 2.2.1 on 2020-08-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='immediate_superior_team_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_members', to='ib_iam.UserTeam'),
        ),
    ]
