# Generated by Django 2.2.1 on 2020-09-15 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0005_auto_20200908_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 15, 17, 8, 48, 853426)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
