# Generated by Django 2.2.1 on 2020-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0006_auto_20200918_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
