# Generated by Django 2.2.1 on 2020-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0007_auto_20200929_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
                ('auth_token_user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
