# Generated by Django 2.2.1 on 2020-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0007_projectteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_iam.Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_iam.Role')),
            ],
        ),
    ]
