# Generated by Django 2.2.1 on 2020-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0007_userauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthtoken',
            name='auth_token_user_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
