# Generated by Django 2.2.1 on 2020-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0008_userauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_prefix',
            field=models.CharField(default='IBWF-{}', max_length=50),
        ),
    ]
