# Generated by Django 2.2.1 on 2020-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_iam', '0008_userauthtoken_auth_token_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthtoken',
            name='auth_token_user_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
