# Generated by Django 2.2.1 on 2020-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_adhoc_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbyinfo',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
