# Generated by Django 2.2.1 on 2020-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_adhoc_tasks', '0002_auto_20200922_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbyinfo',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
